base_config: ./base_sr.yaml
experiment:
  name: espcn_apot_qat

quantization:
  method: apot
  weight_bits: 8
  act_bits: 8
  apot:
    m: 2          # number of additive components
    k: 4          # bits per component (m * k ~= bits)